<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'news.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function news_views_pre_render(&$view) {
  $news_view = array('news', 'news');
  if (in_array($view->name, $news_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
    $news_module_path = drupal_get_path('module', 'news');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css($news_module_path . '/css/news.css');
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function news_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['news']);
}
